# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: gnuton/vitasdk-docker:latest

steps:
- script: sudo apt-get install -qq -y pkg-config
  displayName: 'Install extra dependencies'

- script: sudo apt-get install -qq -y libc6-dev-i386
  displayName: 'Install 32 bit libraries'
  
- script: sudo apt-get install -qq -y zip
  displayName: 'Install zip'
  
- script: |
    git clone https://github.com/Rinnegatamante/math-neon
    cd math-neon
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build libmathneon'

- script: |
    git clone https://github.com/Rinnegatamante/vitaShaRK
    cd vitaShaRK
    vita-libs-gen SceShaccCg.yml shaccg
    cd shaccg
    make -j$(nproc)
    sudo -E make install
    cd ..
    sudo -E cp shacccg.h $VITASDK/arm-vita-eabi/include/psp2/shacccg.h
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build vitaShaRK'

- script: |
    git clone https://github.com/Rinnegatamante/vitaGL
    cd vitaGL
    make -j$(nproc) HAVE_SBRK=1 NO_DEBUG=1 HAVE_SHARK=1
    sudo -E make HAVE_SBRK=1 NO_DEBUG=1 HAVE_SHARK=1 install
  displayName: 'Build vitaGL'

- script: |
    git clone https://github.com/Rinnegatamante/imgui-vita
    cd imgui-vita
    make -j$(nproc)
    sudo -E make install
  displayName: 'Build dear ImGui'

- script: |
    echo "$(cat $VITASDK/version_info.txt)"
    mkdir daedbuild
    cd daedbuild
    cmake -DVITA_RELEASE=1 ../Source -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake
    make -j$(nproc)
    cd ../Data
    zip -9 -r DaedalusX64.zip DaedalusX64
    cd ../Launcher
    make -j$(nproc)
    cp ../Source/sce_sys/icon0.png builder/assets/icon0.png
    cp ../Source/sce_sys/livearea/contents/bg.png builder/assets/bg.png
    cp ../Source/sce_sys/livearea/contents/startup.png builder/assets/startup.png
    zip -9 -r builder.zip builder
  displayName: 'Build Daedalus X64'
    
- task: GitHubRelease@1
  inputs:
    gitHubConnection: release
    repositoryName: Rinnegatamante/DaedalusX64-vitaGL
    tagSource: userSpecifiedTag
    tag: Nightly
    title: 'Nightly $(Build.BuildNumber)'
    action: edit
    assets: |
      daedbuild/DaedalusX64.vpk
      Data/DaedalusX64.zip
      daedbuild/DaedalusX64.elf
      daedbuild/DaedalusX64.self
      Launcher/builder.zip
  displayName: 'Deploy artifacts'
